package.json, src/Lifi.unit.spec.ts, src/balances/utils.int.spec.ts, src/balances/utils.ts, src/executionFiles/bridges/nxtp.execute.ts, yarn.lock
- chore: update types and nxtp sdk
- fix: update TokenAmount usages in tests
- feat(balances): fetch current blockNumber when loading balances
- fix(nxtp): wait until balance rpc contains block number larger than claim block number
=> fix(nxtp): wait until balance rpc contains block number larger than claim block number

package.json, src/executionFiles/bridges/nxtp.execute.ts, src/status.ts, yarn.lock
Our UI has to handle cancelled states as well.
To test I added a pending route to local storage, reloaded the page and resumed the swap:
```
localStorage.setItem('routes', '[{"id":"0x2d377872c3b0c25dab86e6a4215741a8ab6a8b8ed078e274118d8cd0b64e32a7","fromChainId":56,"fromAmountUSD":"40.00","fromAmount":"40000000000000000000","fromToken":{"address":"0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d","symbol":"USDC","decimals":18,"chainId":56,"name":"USD Coin","coinKey":"USDC","priceUSD":"1","logoURI":"https://static.debank.com/image/bsc_token/logo_url/0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d/adee072b10b0db7c5bd7a28dd4fbe96f.png"},"fromAddress":"0x552008c0f6870c2f77e5cC1d2eb9bdff03e30Ea0","toChainId":137,"toAmountUSD":"39.21","toAmount":"39211179","toAmountMin":"39211179","toToken":{"address":"0x2 …
```
=> LF-197: handle cancelled transfers

CHANGELOG.md
History generated using this elaborate hack: https://lukasznojek.com/blog/2020/03/how-to-regenerate-changelog-using-standard-version/
=> docs(CHANGELOG): add changelog history

package.json, src/executionFiles/bridges/hop.int.spec.ts, src/executionFiles/bridges/hop.ts, src/utils.ts, yarn.lock
When sending transfers using a bridge we want to find out when it was actually finished on the receiving chain. This PR tracks transfers from L1 (Ethereum) to L2 (any other chain).
Issue: https://lifi.atlassian.net/browse/LF-241
=> LF-241: fix(hop): find transactions for L1 to L2 transfers

src/executionFiles/StepExecutor.ts, src/executionFiles/allowance.execute.ts, src/executionFiles/bridges/anyswap.execute.ts, src/executionFiles/bridges/cbridge.execute.ts, src/executionFiles/bridges/hop.execute.ts, src/executionFiles/bridges/nxtp.execute.ts, src/executionFiles/exchanges/swap.execute.ts
RP for this frontend PR: https://github.com/lifinance/lifi-web/pull/184
If this is merged before Frontend, the frontend behaviour should not change
=> refactor: check if allowance script can access metamask wallet

README.md, npm.README.md, package.json, src/Lifi.ts, src/Lifi.unit.spec.ts, src/StatusManager.ts, src/StatusManager.unit.spec.ts, src/balances/utils.ts, src/executionFiles/allowance.execute.ts, src/executionFiles/balanceCheck.execute.ts, src/executionFiles/bridges/anyswap.execute.ts, src/executionFiles/bridges/anyswap.ts, src/executionFiles/bridges/cbridge.execute.ts, src/executionFiles/bridges/cbridge.ts, src/executionFiles/bridges/hop.execute.ts, src/executionFiles/bridges/hop.ts, src/executionFiles/bridges/nxtp.execute.ts, src/executionFiles/exchanges/swap.execute.ts, src/types/index.ts, src/utils/errors.ts, src/utils/parseError.ts, src/utils/parseError.unit.spec.ts, src/utils/utils.ts, src/utils/utils.unit.spec.ts, test/fixtures.ts, yarn.lock
* Create custom error types for easier handling
* Improve the parsing of wallet and Lifi Backend related errors.
=> feat: improve handling of wallet & backend errors

src/helpers.ts
Frontend PR: https://github.com/lifinance/lifi-web/pull/187
=> fix!: Typo in getEthereumDecryptionHook

src/StatusManager.ts, src/StatusManager.unit.spec.ts, src/config.ts, src/executionFiles/StepExecutor.ts, src/executionFiles/allowance.execute.ts, src/executionFiles/bridges/bridge.execute.ts, src/executionFiles/exchanges/paraswap.int.spec.ts, src/executionFiles/exchanges/swap.execute.ts, src/executionFiles/switchChain.unit.spec.ts, src/types/internal.types.ts
- feat: add infinite approval to execution settings
- test: disable failing int test
=> feat: add infinite approval to execution settings

e2e/allowance.e2e.ts, jest.e2e.config.js, package.json, src/Lifi.ts, src/allowance/index.ts, src/allowance/utils.ts, src/balances/utils.ts, src/executionFiles/allowance.execute.ts, src/helpers.ts, src/types/internal.types.ts, src/utils/multicall.ts, src/utils/utils.ts
- feat: add token approval methods
- feat: add getApproval methods
=> feat: add token approval methods

src/executionFiles/bridges/bridge.execute.ts
The backend will return NOT_FOUND as statusCode 200 from now on: https://github.com/lifinance/lifi-backend/pull/178
=> feat: adjust status handling to new behaviour

package.json, src/balances/utils.int.spec.ts, yarn.lock
- chore: update types package
- test: exclude outdated unit test
=> fix: fix optimism balance loading

src/execution/allowance.execute.ts
Fix for https://github.com/lifinance/lifi-web/pull/339#issuecomment-1174921152
=> fix: wait for replaced transaction

src/balances/utils.int.spec.ts, src/utils/multicall.ts
Catches parsing errors to avoid making the whole call fail.
=> fix: handle more multicall failure cases

src/execution/StatusManager.ts, src/execution/bridges/bridge.execute.ts, src/execution/exchanges/swap.execute.ts
This needs https://github.com/lifinance/types/pull/89 before release
=> feat: add gasinformation to execution object

package.json, scripts/version.js, src/Lifi.ts, src/helpers.ts, src/types/internal.types.ts, src/version.ts
Sometimes our partners forget to update our SDK and other packages, which leads to unnecessary questions in the support channels etc., and we can avoid some of them. Let's notify them about a new SDK version in the console (Widget will also benefit from reusing this function).
=> feat: add version check

src/Lifi.ts, src/execution/StatusManager.ts, src/execution/StatusManager.unit.spec.ts, src/utils/utils.ts
Native [structuredClone()](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) 👀
CI will be fixed once #113 is merged.
=> refactor: replace deepClone with native structuredClone

src/helpers.ts, src/services/ConfigService.ts, src/types/internal.types.ts
Add widget and SDK version in the header
=> feat: adding widget + sdk version in header

examples/node/README.md
=> Fix: typos

.github/workflows/pull_request_template.md, src/allowance/checkAllowance.ts, src/allowance/checkAllowance.unit.spec.ts, src/allowance/utils.ts, src/execution/StepExecutionManager.ts, src/helpers.ts, src/types/internal.types.ts
Add callbacks to support custom transaction config [LF-763]
Developers can now customize the gas configuration of their on-chain transactions using a callback function. This allows for modification of gas limit, gas price, or priority fee before executing the transaction.
This feature enables developers to customize the gas configuration of their on-chain transactions using a callback function. When a transaction request is sent, the callback function returns the TransactionRequest object to the developer, who can modify the gas configuration such as max gas limit, gas price, or priority fee. Once the developer returns the modified TransactionRequest object, the transaction is executed with the updated configuration. 
This feature is useful for simulating transactions or setting custom …
=> feat: add callbacks to support custom transaction config

package.json, src/execution/StepExecutionManager.ts, src/execution/utils.ts, yarn.lock
Bump `types` package and update status types to the latest.
=> fix: update status types

src/allowance/utils.ts
Add custom gas limit for token approvals
missed implementation for approvals in #137
=> fix: add custom gas limit for approvals LF-2862

src/services/ApiService.ts, src/services/ApiService.unit.spec.ts
Incorrect URL parameters appending
=> fix(getConnections): get connections endpoint error

package.json, yarn.lock
Related to ticket: https://lifi.atlassian.net/browse/LF-4500
=> chore:  bump types package

src/LiFi.unit.spec.ts, src/LiFiInit.unit.spec.ts, src/services/ChainsService.ts
https://lifi.atlassian.net/browse/LF-5504
=> fix: improve error handling during LiFi initialization

src/core/EVM/EVMStepExecutor.ts, src/core/Solana/SolanaStepExecutor.ts, src/utils/errors.ts, src/utils/parseError.ts
Related to https://github.com/lifinance/widget/pull/244 and [LF-7782](https://lifi.atlassian.net/browse/LF-7782)
How it looks like in the widget
[LF-7782]: https://lifi.atlassian.net/browse/LF-7782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add WalletChangedDuringExecution error

src/core/execution.ts
Details [LF-8206](https://lifi.atlassian.net/browse/LF-8206)
[LF-8206]: https://lifi.atlassian.net/browse/LF-8206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update step fromAmount using output of the previous step execution

src/core/EVM/EVMStepExecutor.ts, src/core/EVM/checkAllowance.ts, src/core/EVM/utils.ts, src/core/EVM/waitForTransactionReceipt.ts
[LF-7472](https://lifi.atlassian.net/browse/LF-7472)
[LF-7472]: https://lifi.atlassian.net/browse/LF-7472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: improve transaction receipt polling

src/core/EVM/publicClient.ts, src/core/Solana/connection.ts
RPCs will impose fewer rate limits on us.
=> fix: batch multicall requests

src/core/EVM/EVMStepExecutor.ts, src/core/EVM/checkAllowance.ts, src/core/EVM/parseEVMErrors.ts, src/core/Solana/SolanaStepExecutor.ts, src/core/Solana/parseSolanaErrors.ts, src/core/checkBalance.ts, src/core/stepComparison.ts, src/errors/SDKError.unit.spec.ts, src/errors/baseError.ts, src/errors/baseError.unit.spec.ts, src/errors/errors.ts, src/errors/httpError.ts, src/errors/httpError.unit.spec.ts, src/errors/utils/baseErrorRootCause.unit.spec.ts, src/errors/utils/rootCause.unit.spec.ts
Jira: [LF-8182](https://lifi.atlassian.net/browse/LF-8182)
Follow up improvement to the SDK errors work to remove the html message prop
[LF-8182]: https://lifi.atlassian.net/browse/LF-8182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: remove htmlmessage prop from errors

src/core/EVM/EVMStepExecutor.ts
Details: [LF-9602](https://lifi.atlassian.net/browse/LF-9602)
[LF-9602]: https://lifi.atlassian.net/browse/LF-9602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add fallback for wallet client account address

.github/workflows/publish.yaml, package.json, src/version.ts
Adds provenance statement for NPM. 
https://docs.npmjs.com/generating-provenance-statements
=> ci: add npm provenance

src/core/EVM/waitForBatchTransactionReceipt.ts, src/core/EVM/waitForTransactionReceipt.ts, src/typeguards.ts
Related: [LF-12046](https://lifi.atlassian.net/browse/LF-12046)
[LF-12046]: https://lifi.atlassian.net/browse/LF-12046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: improve replaced transactions handling

examples/node/package.json, examples/node/pnpm-lock.yaml, package.json, pnpm-lock.yaml, src/core/EVM/EVMStepExecutor.ts, src/core/EVM/waitForBatchTransactionReceipt.ts
https://github.com/wevm/viem/pull/3542
=> fix: sync to latest EIP-5792 spec

src/errors/constants.ts, src/errors/httpError.ts
Ticket: https://lifi.atlassian.net/browse/LF-13094
=> fix: add new error codes

examples/node/package.json, examples/node/pnpm-lock.yaml, package.json, pnpm-lock.yaml, src/core/EVM/EVMStepExecutor.ts, src/core/EVM/permits/getNativePermit.ts
Related: [LF-13777](https://lifi.atlassian.net/browse/LF-13777)
[LF-13777]: https://lifi.atlassian.net/browse/LF-13777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: handle wallet 7702 upgrade rejections more gracefully

src/core/EVM/EVMStepExecutor.ts
=> fix: ensure safe access to error cause when handling wallet upgrade rejections

src/core/EVM/EVMStepExecutor.ts, src/core/EVM/parseEVMErrors.ts
Part of the [LF-13777](https://lifi.atlassian.net/browse/LF-13777)
[LF-13777]: https://lifi.atlassian.net/browse/LF-13777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: improve 7702 upgrade rejection error handling

examples/node/package.json, examples/node/pnpm-lock.yaml, package.json, pnpm-lock.yaml, src/core/EVM/abi.ts, src/core/EVM/permits/constants.ts, src/core/EVM/permits/getNativePermit.ts, src/version.ts
[LF-14274](https://lifi.atlassian.net/browse/LF-14274) 
[LF-14274]: https://lifi.atlassian.net/browse/LF-14274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: disable DAI-like permits

src/services/balance.ts, src/services/balance.unit.spec.ts
Add endpoint to fetch cached wallet balances from the backend.
=> feat: add getWalletBalances()

.vscode/settings.json, package.json, src/core/EVM/EVMStepExecutor.ts, src/core/EVM/abi.ts, src/core/EVM/checkAllowance.ts, src/core/EVM/permits/getNativePermit.ts, src/core/EVM/permits/isNativePermitValid.ts, src/core/EVM/switchChain.ts, src/core/EVM/switchChain.unit.spec.ts, src/core/EVM/utils.ts, src/core/execution.ts, src/core/prepareRestart.ts, src/core/processMessages.ts, src/core/types.ts, src/version.ts
Part of [LF-15121](https://lifi.atlassian.net/browse/LF-15121) [LF-12715](https://lifi.atlassian.net/browse/LF-12715)
[LF-15121]: https://lifi.atlassian.net/browse/LF-15121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LF-12715]: https://lifi.atlassian.net/browse/LF-12715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: improve message-based execution flow

src/core/EVM/parseEVMErrors.ts
This error is specific to MetaMask and thrown when the user rejects the signature of the native token transfer, at that point, the bundle id is unknown.
=> fix: handle UnknownBundleIdError error
