src/executionFiles/StepExecutor.ts
src/executionFiles/allowance.execute.ts
src/executionFiles/bridges/cbridge.execute.ts
src/executionFiles/bridges/hop.execute.ts
src/executionFiles/bridges/multichain.execute.ts
src/executionFiles/bridges/nxtp.execute.ts
src/executionFiles/exchanges/swap.execute.ts
src/executionFiles/switchChain.ts
src/executionFiles/switchChain.unit.spec.ts
src/types/internal.types.ts

Switching chains while preparing transaction (`Lifi.getStepTransaction`) causes an unexpected failure when trying to send the transaction (`signer.sendTransaction`) because the signer is configured for the wrong chain.
To prevent that we need to check here again that the user is on the correct chain.

fix: check chain before sending transactions

---

.github/workflows/beta-release.yml
package.json

This action will create and publish beta releases to Github and NPM.
* It listens to pushes to the `main` branch
* It bumps the version number to a beta version (e.g. `0.4.4-beta.0`)
* It updates the changelog 
* Those changes are not persisted in the branch. That means that in normal releases the beta information will not be in the changelog, which is intended

build: add action to release beta versions

---

package.json
src/executionFiles/StepExecutor.ts
yarn.lock

All our bridges now support the /status endpoint and can be handled with the general handler. 
This also implicitly adds Hyphen bridge support :)

feat: use common bridge executor for all known BridgeTools

---

package.json
src/StatusManager.ts
src/executionFiles/bridges/bridge.execute.ts
yarn.lock

It can be that the received token changes due to failures in the destination swap. To be able to show the received token we need to store it in the execution object.
(Requires [types release](https://github.com/lifinance/types/pull/34))

fix: store received token in execution object

---

src/executionFiles/bridges/bridge.execute.ts

We should always continue querying the status endpoint, even if it fails at some point. We hope that the BE recovers and that following requests are successful.

fix: continue status calls after failure

---

src/executionFiles/bridges/bridge.execute.ts
src/utils/parseError.ts

So far we treated a `failed` waiting attempt as "Failed waiting". That's not correct since we query the endpoint until we find a result.
This result can be `FAILED`. In this case we need to show a proper error message.
Before:
Now:

fix: handle status result 'FAILED' correctly

---

src/services/ApiService.unit.spec.ts
src/services/ChainsService.unit.spec.ts
src/services/ConfigService.unit.spec.ts
test/fixtures.ts
yarn.lock

This PR adds the toolDetails property in literal objects and fixes a test that required non EVM chains to have RPC / Multicall information. The latter is a temporary fix while we add complete support for nonEVM chains.

fix: added toolDetails + workaround for non EVM chains testing

---

src/balances/utils.ts
src/utils/multicall.ts
src/utils/multicallAbi.json

My idea was to isolate broken tokens by chunking down to calls of 1 to make sure we get all the other tokens.
Not sure if the log is the best idea but I didn't see another good way how to inform about the broken token.

feat: use tryBlockAndAggregate to fetch balances

---

src/utils/errors.ts
src/utils/parseError.ts

So far we never actually handled the case that between a /routes request and the according /getStepTransaction the quote changed more than the defined slippage.
We need proper handling in the FE to ask the user if they are fine with the new (bad) quote or if they want to abort.
This is on the roadmap.
As a quick solution we decided that the Backend throws an SlippageError if the slippage is 2x the defined slippage. We decided for this large amount to not cause to many failures until we have the real update logic in place. The problem is that this could also happen in the second or third step of a route where the funds of the user already moved a bit. That's why we didn't want to be too restrictive right now.
The current implementation will show the user the following error if the slippage …

feat: handle slippage errors

---

src/allowance/tokenApproval.ts

Previously, Large numbers were being returned in scientific format
Expected: Large values should also be returned as integer string

Return large numbers as string

---

src/execution/ExecutionManager.ts
src/services/ConfigService.unit.spec.ts
src/utils/parseError.ts

Replacing all references of `getChainById` exposed by types package with instance of `ChainService.getChainById`.
LF-1186

Remove references of getChainById exposed by types package

---

src/allowance/tokenApproval.ts
src/connectors.ts
src/helpers.ts
src/services/ApiService.ts
src/services/ApiService.unit.spec.ts
src/utils/errors.ts

Adding a 1 retry policy for API calls with 500 error code

refactor: retry failing API calls on 500 error

---

src/LiFi.ts
src/services/ApiService.ts
src/services/ApiService.unit.spec.ts

Add getConnections endpoint to SDK [LF-1232]
This feature adds the ability to call the getConnections endpoint in the SDK.
This feature fulfills a user request found at https://github.com/lifinance/sdk/issues/87. It adds a new function to the SDK that allows developers to call the getConnections endpoint. This function returns all available connections based on the provided configuration.
To test this feature, follow the steps below:
1. Initialize the SDK.
2. Call getConnections function to retrieve all available connections based on the configuration.
3. Verify that the function returns the expected results.
The getConnections function should return all available connections based on the provided configuration.
[LF-1232]: https://lifi.atlassian.net/browse/LF-1232?atlOrigin=eyJpIjoiNWRkNTl …

feat: adding getConnections endpoint to SDK

---

src/execution/StepExecutor.ts

Switching chains shouldn't be triggered if all actions are done from source chain [LF-1131]
Disable chain switching if all required actions are already completed on the source chain.
Currently, the chain switching window is triggered even if all required actions are already completed on the source chain. This can be an unnecessary interruption for users who only need to wait for the tokens to be received in the receiving chain.
This feature will disable the chain switching window if all required actions are already completed on the source chain, and the user only needs to wait for the tokens to be received in the receiving chain.
1. Bridge USDC from Ethereum to Polygon.
2. Switch your chains to a third network, say Binance.
3. Upon starting the process, the chain would be promptly …

fix: don't trigger chain switch if all actions are done from source chain [LF-1131]

---

src/utils/errors.ts
src/utils/parseError.ts

Sometimes `ethers` can throw INSUFFICIENT_FUNDS error if there is not enough gas to cover the transaction cost. 
Usually, it shouldn't happen because of LI.Fuel and other prevention tools in the widget, but if estimations are wrong, we can see it.

fix: add insufficient funds error

---

src/execution/RouteExecutionManager.unit.spec.ts
src/execution/StepExecutionManager.ts

Fixed "invalid hexlify value" on bridge caused by raw gasLimit

fix: added gasLimit as BigNumber

---

src/services/ApiService.ts
src/services/ApiService.unit.spec.ts

Parsing all params to get the available connections [LF-3826]
Fix the issue where only selected params with array value were being parsed, leaving out other array-based params. Now all array params and all values are parsed and passed in the API request.
Previously, there was an issue where only selected parameters with array values were being parsed, resulting in the exclusion of other array-based parameters. This fix addresses that issue by ensuring that all array parameters and their respective values are parsed and correctly passed in the API request.
No testing is required as this fix is already integrated and tested.
[LF-3826]: https://lifi.atlassian.net/browse/LF-3826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: parsing params in available connections api request

---

src/request.ts
src/services/ConfigService.ts
src/types/internal.types.ts

We want to introduce authentication on the Backend API. We need to be able to set this key in the SDK so it's passed with all requests.

feat: allow to pass api key to all requests

---

package.json
src/LiFi.ts
src/services/ApiService.ts
yarn.lock

The method: `getContractCallQuote` is being deprecated and `getContractCallsQuote` must be used instead.
new method `getContractCallsQuote` is added to enable user to get quotes from multiple contract calls

feat: add multi-contract calls API endpoint

---

package.json
src/LiFi.ts
src/services/ApiService.ts
src/services/ApiService.unit.spec.ts
src/types/internal.types.ts
yarn.lock

There are changes from backend in the request config for the analytics API, 
https://github.com/lifinance/lifi-backend/pull/2770
[API Reference](https://apidocs.li.fi/reference/get_analytics-wallets-wallet-address-1)

fix: wallet analytics API request changes

---

src/LiFi.ts
src/LiFi.unit.spec.ts

Ticket: https://lifi.atlassian.net/browse/LF-7519
Description
- importing balance logic by calling `import * as balance from './balance` caused issues in parcel production builds
Changes:
- changing import of balance handling logic due to issues with using the SDK in the parcel bundler
- updating tests with same import changes and updating the mocking logic for the balance functions
I created a small js app with parcel and react in order to reproduce this issue locally. The changes in this PR fix the issues. 
I also used the local build  in a vite react js project after making the changes just to be sure.

fix: default imports for parcel bundler

---

src/core/EVM/EVMStepExecutor.ts
src/core/EVM/setAllowance.ts
src/core/EVM/switchChain.ts

To enable execution from more complex wallet clients (e.g. smart wallet account clients), the send transaction Viem function is usually overwritten to handle sending these transactions. Viem currently doesn't support the execution of smart accounts in their default send transaction function.
Viem uses a `getAction` util function to execute a given function on the client or default to Viem's default function, which I believe should be used within the SDK.

Execute send transaction from Viem client

---

src/core/EVM/EVMStepExecutor.ts
src/core/EVM/checkAllowance.ts
src/core/types.ts

Recently, token approvals were done by signing a message for tokens supporting [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612). This is great for avoiding executing a transaction to approve tokens only, but it doesn't work for all wallets. 
Permit doesn't work for smart wallet accounts since EIP-2612 omits ERC-1271, which is often used to "sign" messages by smart wallet accounts. 
To still allow smart wallet accounts to use LiFi's SDK, I propose a configuration flag `disableMessageSigning` that skips the Permit logic and always executes a token approval.

Avoid message signing with flag

---

src/core/UTXO/UTXOStepExecutor.ts
src/core/UTXO/utils.ts

This PR:
- adds a check for when a signedPSBT is already final

fix(utxo): add check for when inputs are already final

---

src/core/UTXO/getUTXOPublicClient.ts
src/core/UTXO/utils.ts

This PR decouples bigmi chain ids from LI.FI internal chain ids during bigmi client creation.
part of https://github.com/lifinance/bigmi/pull/31

refactor(utxo): make bigmi chain id dynamic
